# Info
name: fayndee.me
description: A little space where I share about my work and passion.
url: http://fayndee.me
author:
  name: Fang Yuan
  twitter: "@fayndee"
  facebook: fayndee
facebook_app_id: 268895170226028

# Data
collections:
  photos:
    albums:
      - mountain
      - nature
      - urban
      - abstract
      - people
    preview: 3
    output: true
    permalink: /shutterbug/gallery/:title/
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: page_framed_article
      type: article
      teaser_image: article_teaser.jpg
  - scope:
      path: ''
      type: photos
    values:
      layout: page_framed_photo
      type: photo

# Settings
sass:
  style: compressed
permalink: /:categories/:title/
exclude: [README.md, LICENSE.md, .gitignore, Gemfile, Gemfile.lock]

# Plugins
plugins:
  - jekyll-sitemap
